# Generated by Django 2.0.8 on 2018-08-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icecreams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='icecream',
            name='discount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
