# Generated by Django 2.0.8 on 2018-08-27 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icecreams', '0002_icecream_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icecream',
            name='discount',
        ),
    ]
