# Generated by Django 2.0.8 on 2018-08-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('rosat_level', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('processing_type', models.CharField(max_length=30)),
            ],
        ),
    ]
