# Generated by Django 2.0.8 on 2018-08-28 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffee',
            name='description',
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='name',
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='price',
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='processing_type',
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='rosat_level',
        ),
    ]
