# Generated by Django 2.0.8 on 2018-08-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffees', '0003_auto_20180828_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffee',
            name='rosat',
        ),
        migrations.AddField(
            model_name='coffee',
            name='roast',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coffee',
            name='flavour',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='processing',
            field=models.CharField(max_length=100),
        ),
    ]
