# Generated by Django 2.0.8 on 2018-08-31 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffee',
            name='processing_type',
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='rosat_level',
        ),
        migrations.AddField(
            model_name='coffee',
            name='flavour',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coffee',
            name='processing',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coffee',
            name='roast',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coffee',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
